### ISSUE TITLE
Infinite scrolling

### ISSUE THREAD

**Issue by Stephen304** [Stephen304/bitcannon#12]
http://binarymuse.github.io/ngInfiniteScroll/

Because if you scroll more than a few pages, you're doing it wrong.

**Comment by DaPhexion** [comment]
For the love of RMS and Linus, please. Or, we can make a chrome plugin thing.

**Comment by Stephen304** [comment]
I have the api endpoint necessary for this, (`/search/:query/:page/`) but itseems mostly aesthetic to me so I'm trying to get the tracker scraper working so we can sort by seeders.

**Comment by DaPhexion** [comment]
Hey, try to add sort by dates. I mean, some people want the latest version of that game...

**Comment by Stephen304** [comment]
If you sort by seeders, it will often bring later versions of games to the top. Of course dates would work better but it's not included in the torrent archives so I would have to create completely new scraping code to get that info.

After I get seeder / leecher counts I'll look at it again and see if it's necessary to have dates attached.

Also, the more info in the database, the larger it gets. Each torrent is very little info, so adding small amounts of data to each one can increase the total database size by a lot.

**Comment by skinnx86** [comment]
How about a sort (or perhaps filter) by file type?  Many a time I'm after video and I get books too ;-)

**Comment by Stephen304** [comment]
Yes, I have an issue open for this: #31. I'm trying to get it out by next release which I really want to do tonight but no guarantees.
