### ISSUE TITLE
exception: invalid operator: $search

### ISSUE THREAD

**Issue by joshstrange** [Stephen304/bitcannon#22]
None of my searches seem to work as the endpoint that the JS is calling out to is throwing a 404 and returning: 

`{"message":"exception: invalid operator: $search"}`

I am on Ubuntu 13.10, I have imported 2 dumps, and I downloaded the latest release from github.

Let me know if you need any more from me, thanks!

**Comment by Stephen304** [comment]
What search queries are you running? Perhaps I need to escape things before passing it to the api...

**Comment by joshstrange** [comment]
I just ran "adobe" on it as "colbert" didn't work and I just wanted to confirm a successful search. On the second query I opened web debugger tools to check the network tab and saw the response I posted above.

I am running v2.4.9 I checked the mongo site has 2.6.7 as stable. I'm looking into building that on my system right now.

**Comment by Stephen304** [comment]
After a bit of research I am pretty sure the text search operator was introduced in 2.6, so I'm pretty sure updating Mongo will fix the issue. Where did you get 2.4.9, so maybe I can note this in the install guide?

Let me know if it works after updating Mongo.

**Comment by joshstrange** [comment]
I got it from apt-get. I ended up following these instructions [here](http://docs.mongodb.org/manual/tutorial/install-mongodb-on-debian/)

The steps were:

1. `sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10`
2. `echo 'deb http://downloads-distro.mongodb.org/repo/debian-sysvinit dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list`
3. `sudo apt-get update`
4. `sudo apt-get install -y mongodb-org`

**Comment by joshstrange** [comment]
Ok I am no longer getting a 404, it's now a 200 for the `/search/{term}`. I am sending a single word (no odd characters) but I'm getting an empty array (json). I know the site I got a dump from has results for the search term. I can't seem to get anything to come up in the results.

**Comment by joshstrange** [comment]
Ok, forgive me I'm being dense but I dropped into the mongo shell and did a find on the torrents collection and got this: 

![Image of find](https://dl.dropboxusercontent.com/u/2148004/Screenshots/cPOx.png)

Is this expected?

**Comment by Stephen304** [comment]
I might have not made it too clear, but make sure you extract the gz file before you drag it onto the bitcannon binary. if you type in the shell `use bitcannon` and `db.dropDatabase()`, that will clear it out. I will see if I can make the instructions more clear. I want to support dropping gz files right onto the binary, but it might take a bit of time.

**Comment by joshstrange** [comment]
Ok, yeah, I missed that. I will wipe my db and start over. What about the config file? I listed two hourly feeds to import but can I assume that that feature is not ready yet?

**Comment by Stephen304** [comment]
Nope I haven't added that yet. I'm only 1 man! XD

Let me know if BitCannon is working for you now!

**Comment by joshstrange** [comment]
:) If I knew go I would.

**Comment by joshstrange** [comment]
So I wasn't paying attention to the file size (.gz was a little over 500mb but .txt was 1.5GB) and so obviously this is taking a long time to import (not even 1/6th done after 10hrs). Can the server run at the same time an import is running?

**Comment by Stephen304** [comment]
Yes, the server can run at the same time. It's a bit odd taking that long, on my computer the 1.5GB text file took about an hour.

I'm trying to improve the import speed, but it wouldn't make sense to fix the database performance before switching to an embedded database, so it may be a bit before I work on it. I think the best option right now is to only use the 24 hour dumps.

Let me know if you are able to view torrents.

**Comment by joshstrange** [comment]
I will try to run the server when I get home. I just ssh'ed back home and the import is still going. By my count the dump I was trying to import had ~6Mil records and looking at mongo I have ~3Mil (After 17 hours of importing, thank god for screen). 

This is my media server that it is running on but my server is not too shabby, it's got an i7 and the load is not high. It only has 6GB ram but it's not using more that 4 ATM.

I will be using the dailies for sure but wanted to get a large base import first (I'm a data horder).

**Comment by Stephen304** [comment]
After I change database technologies in the coming week, you may have to reimport everything so be aware of that. If you start the bitcannon binary with no arguments, you should be able to view the torrents and search them.

**Comment by joshstrange** [comment]
Are you switching to a different DB all together? If so which one? Also are you looking for any help with the frontend code? I've done a fair amount of work with Angular and while I can't design to save my life I can code up whatever you want. 

I am closing this ticket because this is fixed but I'd like to continue the discussion in a better forum (email or some other discussion platform). I like what you are doing here, keep up the good work!
