### ISSUE TITLE
Adding databases on Linux

### ISSUE THREAD

**Issue by pmwoodward3** [Stephen304/bitcannon#25]
The readme just mentions dragging the .gz to the .exe for windows, what's the process for linux users?

**Comment by Stephen304** [comment]
Which readme are you looking at? I have too many readmes and people keep forgetting to unzip the gz.

For linux just run bitcannon with 1 argument, path to the textfile:
`./bitcannon archive.txt`

**Comment by Stephen304** [comment]
Have you been able to import successfully?

**Comment by pmwoodward3** [comment]
Sorry haven't tried yet, was getting my morning going. Will try now. Does this work if I have a .sql instead of a txt?

**Comment by Stephen304** [comment]
Unfortunately, no. It only works with the ones downloaded from demonoid or kickass at the moment. I'm in the process of switching to an embedded database so it may me another week before I can get back to the import process. We only have 1.5 developers working on this right now.

**Comment by Stephen304** [comment]
Just an update: I've been working late and I've managed to impliment auto importing when the program starts. It pulls urls from the config file. It also now supports dragging gz files onto the binary in addition to the unzipped txt files.

These features will be available in the next release (0.0.5)

**Comment by pmwoodward3** [comment]
What urls would it be importing from by default?

Is there any db right now that has a few different sites, like kickass, opb, nyaa, etc etc?

**Comment by pmwoodward3** [comment]
And thanks for the hard work btw :)

**Comment by Stephen304** [comment]
You're welcome! The v0.0.5 config imports the 24 hour dumps from kickass and demonoid by default. I don't recommend importing the full archives from anything yet as I still need to fix performance issues, and I may need to tweak the database structure sometime (requiring clearing out the database).

If you have BitCannon working, feel free to close this issue.

**Comment by pmwoodward3** [comment]
Awesome! Planning on adding the open pirate bay db dumps?

**Comment by Stephen304** [comment]
I haven't looked at that archive, but I may if the format is convenient.

Otherwise, it would be easy for me to add compatibility for the pirate bay archive titled "The entire Pirate Bay Magnet Archive", available on kickass under that name. Then, with kickass and tpb compatibility, the only thing that the open bay has extra is isohunt so I think that is pretty good.
