### ISSUE TITLE
[critical] Totally needs a select category combined with text search

### ISSUE THREAD

**Issue by Stephen304** [Stephen304/bitcannon#31]
Don't know why I forgot this.

**Comment by Yamakaky** [comment]
+1000. For each search I make, I have 2/3 results marked XXX ^^

**Comment by Stephen304** [comment]
This depends on fixing the browse page performance, as the underlying mechanism that is slow is fetching the categories. I aim to have ths fixed by the end of today.

**Comment by Stephen304** [comment]
I have performance improvements, so I think I can work on the interface tomorrow.

**Comment by Stephen304** [comment]
I think I know how to do this with the aggregation pipeline. Just have to think how to refactor so I don't get 2 large blocks of almost identical code.

**Comment by Stephen304** [comment]
Trying to do this, but angular isn't cooperating. The endpoint is working though, angular doesn't think my category selection is selected. I'd like to get this out by next update.

**Comment by Stephen304** [comment]
Apparently having route params in a child state is a no no for angular. The page itself works, adding the dropdown to the homepage now.
