### ISSUE TITLE
search function  does not work

### ISSUE THREAD

**Issue by 9191521** [Stephen304/bitcannon#33]

**Comment by 9191521** [comment]
press enter nothing happen

**Comment by Stephen304** [comment]
What version of BitCannon are you using and are you sure MongoDB is running?

**Comment by 9191521** [comment]
BC_Windows_v0.0.5
 everything is ok,just no results(which I copy from browse) when searching

**Comment by Stephen304** [comment]
What does the bitcannon command prompt say? It should have automatically imported some torrents.

Also, does the Browse page show categories?

**Comment by 9191521** [comment]
http://i.imgur.com/r8Yh5ar.png

**Comment by Stephen304** [comment]
What version of MongoDB do you have? BitCannon needs 2.6 or greater for text searches to work.

**Comment by 9191521** [comment]
sorry for bothering,I will try the latest MDB

**Comment by Stephen304** [comment]
Don't apologize! It's a common mistake. Let me know if it works!

**Comment by 9191521** [comment]
cool,thx.....

**Comment by Stephen304** [comment]
If 2.6 fixes it, feel free to press the close button on this issue. I'll remember to update the instructions to note this.

**Comment by Stephen304** [comment]
Were you able to get search to work with Mongo2.6?
