### ISSUE TITLE
Guide needed for Centos and debian

### ISSUE THREAD

**Issue by ekoice** [Stephen304/bitcannon#34]
Hi, Im very interested to setup this on a vps, but a guide, step by step is essential.
thank you.

**Comment by Stephen304** [comment]
Due to the amount of linux distributions there are, it's hard to make a guide for all of them.

I would recommend finding a MongoDB install guide for your distro, then see the wiki for the BitCannon set up (which is the same regardless of platform)

**Comment by ekoice** [comment]
any specifications i need to run it smoothly? like ram, hdd, cpu ?

**Comment by Stephen304** [comment]
It mainly depends on how many torrents you aim to keep. Most decent gaming rig type computer should be able to handle a few million, maybe up to 6.

MongoDB uses very little ram, usually around 30MB. CPU usage can spike if you have more than a few million torrents, but it depends on what you are doing (currently the browse page is the only place I have noticed such a spike, I am working on that.)

For hard drive space, it shouldn't get much bigger than 10 even if you try really hard. I imported the full databases of KAT and Demonoid and it was 8GB.

If this helps, you can close this issue.

**Comment by ekoice** [comment]
k, thnx. thanks for the clarification. keep up the good work.
