### ISSUE TITLE
Cannot import openbay-db-dump, all torrents skipped.

### ISSUE THREAD

**Issue by oXis** [Stephen304/bitcannon#35]
[OK!] File opened
[OK!] Extension is valid (I changed csv to txt)
[OK!] Reading initialized
[OK!] Reading completed
         0 torrents imported
         7800659 torrents skipped

Import from website is working.

**Comment by Stephen304** [comment]
Sorry, I haven't added support for it. Soon I will add support for the piratebay magnet link archive, though.

I'm only 1 developer and I'm currently getting tracker scraping to work so we can sort by seeders.

**Comment by oXis** [comment]
Ok, it's not a bug then.
You did a great job! Wish I could help you, but I don't know JS -_-

**Comment by Stephen304** [comment]
If you see any issues in the list that you feel strongly about, add a comment and let me know! That will help me prioritize what to work on.
