### ISSUE TITLE
Angular routes are absolute with a blank api url

### ISSUE THREAD

**Issue by aidanharris** [Stephen304/bitcannon#36]
I changed the API url to bitcannon and everything loaded fine from the reverse proxy with the exception of /browse and /torrent (perhaps other locations too). The attached image demonstrates this:

![bitcannonerror](https://cloud.githubusercontent.com/assets/3309784/5794799/d155b726-9f75-11e4-9332-3e9c59ad3ef6.png)

Everything else for example the styles loads fine.

My reverse proxy is setup as follows:

                <Location /bitcannon/>
                        ProxyPass http://127.0.0.1:1337/
                        ProxyPassReverse http://127.0.0.1:1337/
                </Location>

This is easily fixed by adding another reverse proxy pointing to /bitcannon/bitcannon as follows:

                <Location /bitcannon/bitcannon>
                        ProxyPass http://127.0.0.1:1337
                        ProxyPassReverse http://127.0.0.1:1337
                </Location>

I don't think this should be necessary though hence this issue!

**Comment by Stephen304** [comment]
I'm a little confused about what your set up looks like. Are you running BitCannon on one machine and using reverse proxy to proxy it through another machine?

If your reverse proxy makes BitCannon appear public at hostname.com:4444, The API url should be set to `http://hostname:4444` without a trailing slash

**Comment by aidanharris** [comment]
Having read your comment I've literally just face palmed :stuck_out_tongue_winking_eye: 

I'm running it on the same machine and proxying it over port 443. The mistake I made was inputting the  relative domain (bitcannon) rather than the full URL (https://www.mydomain.com/bitcannon).

Problem Solved!

What I have noticed though is that the API URL is stored in local storage is there any chance an option to configure this could be added to the config.json file?

**Comment by Stephen304** [comment]
I think I know why it was behaving that way, but I'm not absolutely sure. Is that screenshot with the first reverse proxy and a blank api url?

**Comment by aidanharris** [comment]
Not blank I put "bitcannon" as the API url instead of the full URL

**Comment by Stephen304** [comment]
What did the browse request look like with the first reverse proxy and a blank api url?

**Comment by aidanharris** [comment]
With a blank api URL the browse request is going to https://www.mydomain.com/browse instead of https://www.mydomain.com/bitcannon/browse

**Comment by Stephen304** [comment]
Ah, as I expected. I accidentally put the slash before the route so all of them are absolute paths with a blank api url. I didn't expect anyone to host from a different directory.

I think I can fix this easily, but I'll have to test a bit. If I use relative paths it may work fully or maybe just partially. It would definitely also be good to be able to define the bitcannon base url in the `config.json`, but I don't see an obvious way to accomplish this yet, as all the web assets are converted into raw bytes and compiled into the binary.

Another option is if you put the actual web assets in the /bitcannon folder with the default api url set. I'll be sure to release a zip of just the web assets in the next release for this purpose.

I'll comment on this issue as I make progress.

**Comment by Stephen304** [comment]
Simply removing the preceding slash on the web app seems to have fixed this. It will definitely be in the next release.
