### ISSUE TITLE
Embedded TingoDB support 

### ISSUE THREAD

**Issue by nwgat** [Stephen304/bitcannon#37]
a drop-in mongodb compatible embedded database 
http://www.tingodb.com/

NodejS-rTorrent has implemented support for it
https://github.com/roastlechon/nodejs-rtorrent

@roastlechon i summon you! 
how easy was it to implement?

**Comment by roastlechon** [comment]
It was easy because I was using Mongoose. bigcannon seems to be written in Go though.

**Comment by Stephen304** [comment]
It would have to work in Go, it seems to only be embedded in JS.

**Comment by Stephen304** [comment]
If you have any other thoughts about it, let's keep all the related info on issue #23.
