### ISSUE TITLE
Provide a release download url can be downloadable via wget

### ISSUE THREAD

**Issue by unixfox** [Stephen304/bitcannon#38]
You provide the release on mega links but it's impossible to wget mega via terminal. Can you provide Bitcannon on other hosting ?

**Comment by oXis** [comment]
You can use Megatools for that.
https://github.com/megous/megatools

**Comment by unixfox** [comment]
Megatools doesn't work, i've tried it.

**Comment by Stephen304** [comment]
Not many file hosting sites allow direct linking, so I'm not exactly sure where I could upload it that would allow wget to download it directly.

Do you have any suggestions?

**Comment by unixfox** [comment]
You can host on your server for exemple or via anonymous ftp.

**Comment by unixfox** [comment]
If you want you can setup a free server apache with [Openshift](https://openshift.redhat.com).

**Comment by unixfox** [comment]
I've found a good article about [host direct linking](http://techapple.net/2014/05/5-free-file-hostingsharing-cloud-storage-sites-directhot-link-support-cloudlinker-v2-0-direct-link-maker/). I think dropbox is the solution.

**Comment by Stephen304** [comment]
My only concern is that the company I host it on will view it as piracy software and cause issues.

Is your use case that you have a server with no graphical environment?

**Comment by unixfox** [comment]
I've a bad connection because I'm on a hotspot. It's easier wget than moving directly via sftp each update.

**Comment by Stephen304** [comment]
I'll see if I can come up with a good place to put it later today when I'm off work.

**Comment by unixfox** [comment]
If you do not find hosting I can provide you an ftp space connected to an Apache server on my vps.

**Comment by unixfox** [comment]
I've found a [good tutorial](http://hacktracking.blogspot.be/2013/07/download-mega-files-from-command-line.html) to download mega links via command line.
