### ISSUE TITLE
[Feature Request] Integrate Torrent Client

### ISSUE THREAD

**Issue by corani** [Stephen304/bitcannon#47]
I've been looking around, and it seems Taipei-Torrent is a pretty complete BT client. Now, wouldn't it be great to have the client _embedded_ into BitCannon?

This could also be leveraged to fetch Info-Hash dumps over BT, instead of over HTTP.

**Comment by Stephen304** [comment]
I'm not sure how I feel about this one. I think most people already have a bittorrent client that they like, and I don't want to try to do everything with bitcannon. If someone wants to use bitcannon to host a torrent site, they probably don't want a torrent client to be integrated.

The dht code for fetching info hashes over bt protocol is a very small part of taipei torrent, so I'm opting to pull bits of taipei torrent out and use them as modules instead.
