### ISSUE TITLE
[Feature Request] Add import date

### ISSUE THREAD

**Issue by corani** [Stephen304/bitcannon#48]
While the magnet link dumps don't contain dates, adding an import date (first seen) is a reasonable alternative, especially if you're using daily/hourly updates. It would at least get the dates more-or-less correct from the time you start using the application.

**Comment by Stephen304** [comment]
Of course! I need to update the ui a tad to squeeze it in but I think it would be very useful to sort by import date. I imagine 2 sorting modes, by seeders and by most recently imported.

I think I can add this later today.

**Comment by Stephen304** [comment]
The import time is stored. I'll make an issue for ui updates, and hopefull get around to it soon.
