### ISSUE TITLE
Feature request: Torrent list traditional view

### ISSUE THREAD

**Issue by duytrung** [Stephen304/bitcannon#53]
Hi,
I used BC and found it's behavior need to be changed, IMHO, :-)
Bitcannon display list like this:
Torrent name -> Category
Traditional tradition list view appears like:
Type/Genre -> Torrent name -> Date -> Magnet URL
or 
Root > Ebooks -> Torrent name - Magnet url

Here is the reason why:
+There is no need to select the torrent, then the browser loads to "download page" and display the "download" button. It's wasting time.
+The text file API is so simple, why make it more complex by adding another step to download page?
+Displaying the webpage as traditional html page help bitcannon less using queries like: "started get /torrent/hash/ for 127...1: complete for ... This is good for learning to program with database and stuffs like that.
+From the text API, just sort by category and generate a html or at least a local dynamic webpage for each category. This is short and simple. There is no need to download a mongodb, use a sqlite is adequate for the "daily" dumps. sqlite is able to handle large database.

This is my opinion. I found that mongo is so big :-D.

**Comment by Stephen304** [comment]
The downloads page is meant for all the extra info like source link. You will see in the next release, there is a lot more than in v0.0.6.

I'll add and reorder the search results page soon. I haven't changed it since I initially made that page, so it's more of a placeholder.

**Comment by duytrung** [comment]
Thanks for your software. You did a great job @Stephen304. Congrats and best wishes :+1:

**Comment by Stephen304** [comment]
I've just added a lot of info to the search page. I still have to optimize it by not sending an extra request on the torrent details page, but that will come later.
