### ISSUE TITLE
On search results page, 'Category', 'Name', and 'Imported' columns are blank

### ISSUE THREAD

**Issue by HighCommander4** [Stephen304/bitcannon#56]
Just upgraded to 0.1.0. However, I'm finding that with this new version, the 'Category', 'Name', and 'Imported' columns in the search results page are blank. Please see the attached image.

![bitcannon-blank-columns](https://cloud.githubusercontent.com/assets/1751085/5995331/3cff6a88-aa5e-11e4-9874-acdf7400f25e.png)

**Comment by HighCommander4** [comment]
Also the "2014 years ago" looks suspect. Is it related to having to clear out the database when upgrading versions, as mentioned in https://github.com/Stephen304/bitcannon/issues/49#issuecomment-71150141? If so, how do I do the clearing?

**Comment by Stephen304** [comment]
If you know where the MongoDB data folder is, you can delete the contents (everything in /data/db on most systems)

**Comment by HighCommander4** [comment]
Confirmed, clearing the database fixes the problem. (You might want to mention this in the docs too, for peopel upgrading versions :))
