### ISSUE TITLE
add date-time to command line output

### ISSUE THREAD

**Issue by marafa** [Stephen304/bitcannon#60]
Currently the output looks like this:
[OK!] Starting to import from url:
      http://bitsnoop.com/api/latest_tz.php?t=all
[!!!] I was given a URL that doesn't end in .txt or .txt.gz.
      I'll assume it's regular text.
[OK!] Compression detection complete
[OK!] Reading initialized
[OK!] Reading completed
      34 torrents imported
      64 torrents skipped

for logging purposes, it should have the prefix `bitcannon Feb 04 08:23:59.000` preceding each line 
- date format can be any legible format (including yyyymmdd-hhmmss ) so long as it is not unix time ;)

**Comment by Stephen304** [comment]
If I switch from fmt to log it should add timestamps.
