### ISSUE TITLE
search function not working?

### ISSUE THREAD

**Issue by marafa** [Stephen304/bitcannon#63]
i browse my db and picked a word and tried searching for it. no results were returned
so i tried case sensitive. no results were found
so i just stuck the vowel "a" only.
again. no results were found

at this point. i am concluding the search function is not working

**Comment by Stephen304** [comment]
Can you provide some details like what you have imported to the database and what the bitcannon log window shows?

**Comment by marafa** [comment]
hi
i am using the default json file. i have crontab set up to kill and then launch the app every hour. 

currently i have 44000 torrents in the db

i did not upgrade from a previous version.

i am using the default mongodb of centos6 mongodb-server-2.4.12-2.el6.x86_64 - why is this an issue?

**Comment by marafa** [comment]
the latest version of mongodb on fedora is 2.4.9 - very funny

**Comment by Stephen304** [comment]
You will need to use mongodb 2.6 as 2.4 doesn't have the functions necessary to do flexible text searches.
