### ISSUE TITLE
[critical] Seeder/Leecher count auto update

### ISSUE THREAD

**Issue by Stephen304** [Stephen304/bitcannon#7]
This might be tricky. Would like to use clientsided things to reduce server load but that might be tough.

**Comment by Stephen304** [comment]
UDP tracker scraping test works. About to integrate this into bitcannon.

**Comment by Stephen304** [comment]
Functions added - needs a scheduler to queue torrents.

**Comment by DaPhexion** [comment]
[There's this](http://bitsnoop.com/info/api.html) but no file size.

**Comment by Stephen304** [comment]
That may be useful, but the rate limiting theoretically would make it take 24 days to request something like seeders / leechers for 6 million torrents.

I have a UDP tracker scraper library (not much of a library though) at https://github.com/Stephen304/goscrape and I think I should be able to work on it for a bit to allow bulk scraping as the UDP specs allow multiple scrape requests in 1 packet. I think 15 scrape requests per packet sounds like a reasonable number, and 1 packet per second also sounds reasonable, resulting in 4 days for 6 million torrents.

I do notice that bitsnoop has the last hour of torrents served in plain text so I will definitely add support for that as an importing source! Thank's for pointing me that way!

**Comment by Stephen304** [comment]
Scraping finally almost works. The endpoint functions and updates the torrent records. I just have to add a refresh button to trigger it, as well as a stale torrent fetcher to feed the scrape worker.

**Comment by Stephen304** [comment]
Manual refresh of the tracker stats works, but the scraping library needs improvement. Leaving this issue open for when I do auto scraping in the background.

**Comment by corani** [comment]
You could "auto scape" only the results of a user query (asynchronous), or even only when you open the details for a given result.

**Comment by Stephen304** [comment]
I have nearly completed this in the last commit. I just need to make config options to adjust the scraping speed.
