### ISSUE TITLE
[Enhancement] Add wiki documentation about API endpoints

### ISSUE THREAD

**Issue by OmgImAlexis** [stephen304/bitcannon#82]
I'd love to add support to a project I'm working for this but there's no way I can without proper documentation.

**Comment by Stephen304** [comment]
I don't have very much time to maintain this but if you skim the api file you should find all the endpoints in there. What kind of project is it?

**Comment by Stephen304** [comment]
Here is the relevant segment of code. The routes are self explanatory, the parameters are denoted with :<parameter>, and they are named sensible things.

	api.M.Get("/stats", torrentDB.Stats)
	api.M.Get("/browse", torrentDB.Categories)
	api.M.Get("/browse/:category", torrentDB.Browse)
	api.M.Get("/torrent/:btih", torrentDB.Get)

	api.M.Get("/search/:query", torrentDB.Search)
	api.M.Get("/search/:query/s/:skip", torrentDB.Search)
	api.M.Get("/search/:query/c/:category", torrentDB.Search)
	api.M.Get("/search/:query/c/:category/s/:skip", torrentDB.Search)

	api.M.Get("/scrape/:btih", apiScrape)

**Comment by OmgImAlexis** [comment]
Since I don't know GO I wasn't sure where to look, thanks. There's two projects, [SickRage](https://github.com/SiCKRAGETV/SickRage) and my personal project that's similar but written in nodejs [Olivia](https://github.com/omgimalexis/Olivia).

That should be fine, thank you. Is there any plans on normalising category names? I've noticed some of my imports use `video tv` and others use just `tv`. Is there a way to search the api for both or either? Maybe something like `tv|video tv`? Also I've noticed that the api seems to be case sensitive.

**Comment by Stephen304** [comment]
Yeah the category system needs some work. I wanted to add a whitelist of categories and category aliases to restrict and combine categories on import. Unfortunately, I don't have time to actively maintain bitcannon at the moment as side projects have negatively impacted school work.

**Comment by OmgImAlexis** [comment]
If it wasn't written in go I'd be submitting PRs left, right and center but I only know nodejs. :cry:
