### ISSUE TITLE
Add proxy support

### ISSUE THREAD

**Issue by papampi** [Stephen304/bitcannon#88]
Please add proxy support.
many countries block torrent sites
please add proxy support so we can add our local proxy server.
Thanks

**Comment by duramato** [comment]
@papampi you can change the dumps URLs to a proxified one ,on the config file

**Comment by papampi** [comment]
can you please explain how can I add local  tor or privoxy?

**Comment by duramato** [comment]
@papampi i didnt meant tor or proxy ,but a url proxy

**Comment by papampi** [comment]
well, I live in a country where all are blocked and cant use url proxies
if its possible to add network proxy will be awesome
tried with proxychains, but doesnt work with it either

**Comment by stephen304** [comment]
You should probably look into transparent proxy setups. Bitcannon will request any url you give it, so you can use iptables, openvpn, tap/tun interfaces, host file settings with a proxy app, basically any method to create a transparent proxy.

You may want to read this page if you want to proxy over tor: https://trac.torproject.org/projects/tor/wiki/doc/TransparentProxy

I doubt I will have time to implement support for socks.

**Comment by papampi** [comment]
Thanks a lot Stephan,
will try that solution, although its way over my knowledge.
and you got me wrong, I didnt ask for socks support, an http proxy support will do the job.
any way dont bother if its too much to ask for.

**Comment by stephen304** [comment]
Ah I misunderstood. Anyways, bitcannon should work with an http proxy if you have one running and put the proxied url in the config. I'll close this issue, but feel free to contact me with any further questions you have.

**Comment by papampi** [comment]
Can you please provide an example of a proxied url to put in config?
in sickrage config we have 
proxy_setting = http://ip:port

any thing similar I can add to config ?

**Comment by stephen304** [comment]
That looks like a socks proxy setting.

If you have a cgi proxy site you can change something like
`http://bitsnoop.com/api/latest_tz.php?t=all`

to 
`https://www.vtunnel.us/index.php/1000000A/b41fe1cd94294037e7f3359db694f2b8067f6b4a51d5bce9edbb0699bdee6513f9fc9cbc7a6e7ac64319305`

If you use vtunnel (or really any cgi proxy), make sure to uncheck "Show URL Form" and make sure the proxy doesn't add anything to the page.

Keep in mind that free proxies might not work well for this, and most have ads. For a more robust solution you should probably get a VPN or set up transparent proxying on your computer.
