### ISSUE TITLE
Database location

### ISSUE THREAD

**Issue by duramato** [Stephen304/bitcannon#90]
Where are the db located?  
Mongodb has a limit of 3gb on 32b systems and ive reached it,so when i try and start mongo it doesnt start at all.The only solution is to delete the currect db and start a new one

**Comment by stephen304** [comment]
The location depends on how you installed it. By default I think it should be in a folder on C:.

**Comment by duramato** [comment]
@Stephen304 Im running on linux, and ive figured  it was on /var/lib/mongodb/
Thanks anyway :smiley:
